# This is a basic workflow to help you get started with Actions

name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
        service_account: ${{ secrets.SERVICE_ACCOUNT }}

    # - name: Deploy client to App Engine
    #   id: deploy-client
    #   uses: google-github-actions/deploy-appengine@v1.2.7
    #   with:
    #     deliverables: client/app.yaml
    #     project_id: ${{ secrets.GCP_PROJECT }}

    - name: Deploy server to App Engine
      id: deploy-server
      uses: google-github-actions/deploy-appengine@v1.2.7
      with:
        deliverables: server/app.yaml
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Test
      run: curl "${{ steps.deploy-client.outputs.url }}"
